export const countryCodes = [
  { code: "+91", flag: "🇮🇳", label: "India" },
  { code: "+1", flag: "🇺🇸", label: "United States" },
  { code: "+44", flag: "🇬🇧", label: "United Kingdom" },
  { code: "+61", flag: "🇦🇺", label: "Australia" },
  { code: "+971", flag: "🇦🇪", label: "UAE" },
  { code: "+966", flag: "🇸🇦", label: "Saudi Arabia" },
  { code: "+974", flag: "🇶🇦", label: "Qatar" },
  { code: "+965", flag: "🇰🇼", label: "Kuwait" },
  { code: "+968", flag: "🇴🇲", label: "Oman" },
  { code: "+65", flag: "🇸🇬", label: "Singapore" },
  { code: "+60", flag: "🇲🇾", label: "Malaysia" },
  { code: "+86", flag: "🇨🇳", label: "China" },
  { code: "+81", flag: "🇯🇵", label: "Japan" },
  { code: "+82", flag: "🇰🇷", label: "South Korea" },
  { code: "+49", flag: "🇩🇪", label: "Germany" },
  { code: "+33", flag: "🇫🇷", label: "France" },
  { code: "+39", flag: "🇮🇹", label: "Italy" },
  { code: "+34", flag: "🇪🇸", label: "Spain" },
  { code: "+31", flag: "🇳🇱", label: "Netherlands" },
  { code: "+7", flag: "🇷🇺", label: "Russia" },
  { code: "+27", flag: "🇿🇦", label: "South Africa" },
  { code: "+55", flag: "🇧🇷", label: "Brazil" },
  { code: "+1-CA", flag: "🇨🇦", label: "Canada" },
  { code: "+64", flag: "🇳🇿", label: "New Zealand" },
  { code: "+94", flag: "🇱🇰", label: "Sri Lanka" },
  { code: "+880", flag: "🇧🇩", label: "Bangladesh" },
  { code: "+92", flag: "🇵🇰", label: "Pakistan" },
];
